import React, { useState } from "react";

// Mock reports metadata database
const INITIAL_REPORTS = [
  {
    id: "REP-9921",
    name: "AI Face Sighting Analysis - Case #1 Sarah Connor",
    caseId: "1",
    target: "Sarah Connor",
    type: "AI Recognition Sighting Audit",
    generatedBy: "System Operator",
    date: "2026-08-22",
    size: "24.5 KB",
    dataCsv: "Report ID,Sighting ID,Camera,Time,Confidence\nREP-9921,SI-901,Camera 4,14:23,96.5%\nREP-9921,SI-889,Camera 12,11:05,94.2%"
  },
  {
    id: "REP-9877",
    name: "Surveillance Audit Log - East Sector Hub",
    caseId: "All",
    target: "Multiple Targets",
    type: "CCTV Stream Audit",
    generatedBy: "Security Admin",
    date: "2026-08-21",
    size: "112.8 KB",
    dataCsv: "Report ID,Camera ID,Location,Flagged Detections,Active Hours\nREP-9877,CAM-04,East Exit,14,24 hours\nREP-9877,CAM-07,Bus Bay C,6,24 hours"
  },
  {
    id: "REP-9812",
    name: "Comprehensive Investigation Briefing - Case #2 John Doe",
    caseId: "2",
    target: "John Doe",
    type: "Full Briefing Dossier",
    generatedBy: "Lead Inspector",
    date: "2026-08-19",
    size: "48.2 KB",
    dataCsv: "Report ID,Field,Status,Notes\nREP-9812,Last Seen,Convenience Store,Flagged on camera scan\nREP-9812,Contact Person,Jane Doe,Primary relative contacted"
  },
  {
    id: "REP-9705",
    name: "Weekly AI Detection Engine Performance Summary",
    caseId: "System",
    target: "Global Metrics",
    type: "Engine Performance Diagnostic",
    generatedBy: "System Engine Auto-report",
    date: "2026-08-15",
    size: "15.6 KB",
    dataCsv: "Report ID,Engine Version,Total Frames Scanned,Accuracy Threshold,False Positives\nREP-9705,v3.8.4,1420950,0.85,0.015%"
  }
];

export default function ReportsPage() {
  const [reports, setReports] = useState(INITIAL_REPORTS);
  const [searchTerm, setSearchTerm] = useState("");
  const [typeFilter, setTypeFilter] = useState("all");
  const [caseFilter, setCaseFilter] = useState("all");
  const [successToast, setSuccessToast] = useState("");

  // Handler to generate and download dynamic CSV mockup
  const handleDownloadCsv = (report) => {
    try {
      const blob = new Blob([report.dataCsv], { type: "text/csv;charset=utf-8;" });
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.setAttribute("href", url);
      link.setAttribute("download", `${report.id}_${report.target.replace(/\s+/g, "_")}.csv`);
      link.style.visibility = "hidden";
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      
      setSuccessToast(`Successfully downloaded CSV for ${report.id}!`);
      setTimeout(() => setSuccessToast(""), 3000);
    } catch (e) {
      console.error(e);
      alert("Failed to export report CSV");
    }
  };

  // Handler to simulate PDF compilation
  const handleDownloadPdf = (report) => {
    setSuccessToast(`Compiling PDF Dossier for ${report.id}... Started download.`);
    setTimeout(() => setSuccessToast(""), 3000);
    
    // Create simple text/plain file as mockup PDF
    const mockPdfContent = `
=========================================
      MISSING PERSON AI DETECTION REPORT
=========================================
Report ID: ${report.id}
Title: ${report.name}
Reference: Case ID #${report.caseId}
Target Subject: ${report.target}
Report Type: ${report.type}
Generated By: ${report.generatedBy}
Date Compiled: ${report.date}
Format: Platform Intelligence PDF
=========================================
Generated Data Details:
${report.dataCsv}
=========================================
End of Dossier. Confidential.
    `;
    const blob = new Blob([mockPdfContent], { type: "text/plain;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.setAttribute("href", url);
    link.setAttribute("download", `${report.id}_dossier.txt`);
    link.style.visibility = "hidden";
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  // Filter logic
  const filteredReports = reports.filter(rep => {
    if (typeFilter !== "all" && rep.type !== typeFilter) return false;
    if (caseFilter !== "all") {
      if (caseFilter === "system" && rep.caseId !== "System") return false;
      if (caseFilter === "active" && ["1", "2", "3"].indexOf(rep.caseId) === -1) return false;
    }
    if (searchTerm) {
      const q = searchTerm.toLowerCase();
      return (
        rep.name.toLowerCase().includes(q) ||
        rep.id.toLowerCase().includes(q) ||
        rep.target.toLowerCase().includes(q) ||
        rep.generatedBy.toLowerCase().includes(q)
      );
    }
    return true;
  });

  // Analytics data for the chart representation
  const weeklyTrends = [
    { label: "Mon", scans: 142, matches: 3, glow: "0 0 10px rgba(212,247,114,0.1)" },
    { label: "Tue", scans: 198, matches: 8, glow: "0 0 15px rgba(212,247,114,0.2)" },
    { label: "Wed", scans: 310, matches: 15, glow: "0 0 25px rgba(212,247,114,0.4)" },
    { label: "Thu", scans: 240, matches: 9, glow: "0 0 15px rgba(212,247,114,0.2)" },
    { label: "Fri", scans: 412, matches: 24, glow: "0 0 35px rgba(212,247,114,0.6)" },
    { label: "Sat", scans: 560, matches: 31, glow: "0 0 45px rgba(212,247,114,0.8)" },
    { label: "Sun", scans: 320, matches: 12, glow: "0 0 20px rgba(212,247,114,0.3)" }
  ];

  const maxScans = Math.max(...weeklyTrends.map(d => d.scans));

  return (
    <div className="content">
      {/* TOAST NOTIFICATION */}
      {successToast && (
        <div style={{
          position: "fixed",
          bottom: "24px",
          right: "24px",
          background: "var(--panel)",
          border: "1px solid var(--accent-lime)",
          boxShadow: "var(--shadow-lime)",
          padding: "16px 24px",
          borderRadius: "var(--radius-md)",
          color: "var(--accent-lime)",
          zIndex: 1000,
          fontWeight: "600",
          display: "flex",
          alignItems: "center",
          gap: "10px",
          animation: "slideIn 0.3s ease"
        }}>
          <span>🔔</span> {successToast}
        </div>
      )}

      {/* HEADER CARD */}
      <section className="control-card" style={{ display: "flex", flexDirection: "row", justifyContent: "space-between", alignItems: "center", flexWrap: "wrap", gap: "16px" }}>
        <div>
          <div className="card-label">ANALYTICS & DOSSIERS</div>
          <h2 style={{ fontFamily: "Lora, serif", fontSize: "24px" }}>Platform <em>Intelligence</em> Reports</h2>
          <p style={{ color: "var(--text-sage)", fontSize: "14px", marginTop: "4px" }}>
            Query, inspect, and export compiled sighting stats, performance summaries, and investigative case files.
          </p>
        </div>
      </section>

      {/* STATS OVERVIEW CARDS */}
      <section className="stats-grid">
        <div className="stat-card">
          <div className="stat-icon">📊</div>
          <div>
            <span>TOTAL REPORTS</span>
            <strong>{reports.length} Logs</strong>
          </div>
        </div>
        <div className="stat-card">
          <div className="stat-icon">📈</div>
          <div>
            <span>AVG SIMILARITY</span>
            <strong>86.4%</strong>
          </div>
        </div>
        <div className="stat-card">
          <div className="stat-icon">🔌</div>
          <div>
            <span>ACTIVE CCTV HOOKS</span>
            <strong>16 Feeds</strong>
          </div>
        </div>
        <div className="stat-card">
          <div className="stat-icon">⚡</div>
          <div>
            <span>SYSTEM ACCURACY</span>
            <strong className="online">99.8%</strong>
          </div>
        </div>
      </section>

      {/* CUSTOM VISUALIZATION CHART */}
      <section className="analysis-section" style={{ padding: "28px" }}>
        <div className="section-header" style={{ marginBottom: "20px" }}>
          <div>
            <div className="card-label">AI ENGINE SIGHTINGS & SURVEILLANCE LOAD</div>
            <h3 style={{ fontFamily: "Lora, serif", fontSize: "18px" }}>Weekly Detection Analytics</h3>
          </div>
          <span style={{ fontSize: "12px", color: "var(--text-sage)" }}>Updated hourly</span>
        </div>

        {/* Custom HTML/CSS Bar Graph */}
        <div style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "flex-end",
          height: "220px",
          padding: "20px 10px 10px 10px",
          background: "rgba(11, 30, 20, 0.5)",
          borderRadius: "var(--radius-md)",
          border: "1px solid var(--border)",
          position: "relative"
        }}>
          {/* Grid lines background */}
          <div style={{ position: "absolute", left: 0, right: 0, top: "25%", borderBottom: "1px dashed rgba(255,255,255,0.05)" }} />
          <div style={{ position: "absolute", left: 0, right: 0, top: "50%", borderBottom: "1px dashed rgba(255,255,255,0.05)" }} />
          <div style={{ position: "absolute", left: 0, right: 0, top: "75%", borderBottom: "1px dashed rgba(255,255,255,0.05)" }} />

          {weeklyTrends.map((data, index) => {
            const scanPercentage = (data.scans / maxScans) * 100;
            return (
              <div 
                key={index} 
                style={{ 
                  display: "flex", 
                  flexDirection: "column", 
                  alignItems: "center", 
                  flex: 1, 
                  zIndex: 2 
                }}
              >
                {/* Tooltip on hover */}
                <div className="chart-tooltip" style={{
                  background: "var(--panel)",
                  border: "1px solid var(--accent-lime)",
                  color: "#fff",
                  fontSize: "10px",
                  padding: "4px 8px",
                  borderRadius: "4px",
                  marginBottom: "8px",
                  fontWeight: "700",
                  textAlign: "center",
                  boxShadow: data.glow
                }}>
                  <div style={{ color: "var(--accent-lime)" }}>{data.matches} Matches</div>
                  <div style={{ color: "var(--text-sage)", fontSize: "9px" }}>{data.scans} Scans</div>
                </div>

                {/* Vertical Bar */}
                <div style={{
                  width: "28px",
                  height: `${scanPercentage * 1.2}px`, // Scaled for display
                  background: `linear-gradient(180deg, var(--accent-lime) 0%, rgba(212,247,114,0.1) 100%)`,
                  borderRadius: "6px 6px 0 0",
                  boxShadow: data.glow,
                  transition: "all 0.4s cubic-bezier(0.16, 1, 0.3, 1)"
                }} />
                
                {/* X Axis Label */}
                <span style={{ fontSize: "11px", color: "var(--text-sage)", marginTop: "10px", fontWeight: "600" }}>{data.label}</span>
              </div>
            );
          })}
        </div>
      </section>

      {/* FILTER & DATA SECTION */}
      <section className="analysis-section" style={{ padding: "28px" }}>
        <div className="section-header" style={{ marginBottom: "20px", display: "flex", flexWrap: "wrap", gap: "16px", justifyContent: "space-between", alignItems: "center" }}>
          <h3 style={{ fontFamily: "Lora, serif", fontSize: "18px", color: "var(--accent-lime)" }}>Generated Records</h3>
          
          <div style={{ display: "flex", gap: "12px", flexWrap: "wrap", alignItems: "center" }}>
            {/* Filter inputs */}
            <select
              value={typeFilter}
              onChange={(e) => setTypeFilter(e.target.value)}
              style={{ padding: "6px 14px", fontSize: "12px" }}
            >
              <option value="all">All Report Types</option>
              <option value="AI Recognition Sighting Audit">AI Sighting Audit</option>
              <option value="CCTV Stream Audit">CCTV stream</option>
              <option value="Full Briefing Dossier">Case Briefing</option>
              <option value="Engine Performance Diagnostic">Diagnostics</option>
            </select>

            <select
              value={caseFilter}
              onChange={(e) => setCaseFilter(e.target.value)}
              style={{ padding: "6px 14px", fontSize: "12px" }}
            >
              <option value="all">All Targets</option>
              <option value="active">Active Cases</option>
              <option value="system">System Only</option>
            </select>

            <input
              type="text"
              placeholder="Search reports..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              style={{ padding: "6px 16px", fontSize: "12px", width: "200px" }}
            />
          </div>
        </div>

        {/* Responsive Table Wrapper */}
        <div style={{ overflowX: "auto" }}>
          <table style={{ width: "100%", borderCollapse: "collapse", textAlign: "left", fontSize: "13px" }}>
            <thead>
              <tr style={{ borderBottom: "1px solid var(--border)", color: "var(--text-sage)", fontWeight: "700" }}>
                <th style={{ padding: "12px 16px" }}>Report ID</th>
                <th style={{ padding: "12px 16px" }}>Name / Title</th>
                <th style={{ padding: "12px 16px" }}>Subject</th>
                <th style={{ padding: "12px 16px" }}>Type</th>
                <th style={{ padding: "12px 16px" }}>Date</th>
                <th style={{ padding: "12px 16px" }}>Size</th>
                <th style={{ padding: "12px 16px", textAlign: "right" }}>Actions</th>
              </tr>
            </thead>
            <tbody>
              {filteredReports.length === 0 ? (
                <tr>
                  <td colSpan="7" style={{ textAlign: "center", padding: "40px", color: "var(--text-sage)" }}>
                    No reports match selection filters.
                  </td>
                </tr>
              ) : (
                filteredReports.map((report) => (
                  <tr 
                    key={report.id} 
                    style={{ 
                      borderBottom: "1px solid var(--border-light)", 
                      background: "transparent",
                      transition: "background 0.2s ease" 
                    }}
                    onMouseEnter={(e) => e.currentTarget.style.background = "rgba(255,255,255,0.02)"}
                    onMouseLeave={(e) => e.currentTarget.style.background = "transparent"}
                  >
                    <td style={{ padding: "16px", fontWeight: "700", color: "var(--accent-lime)" }}>{report.id}</td>
                    <td style={{ padding: "16px", fontWeight: "500" }}>{report.name}</td>
                    <td style={{ padding: "16px" }}>{report.target}</td>
                    <td style={{ padding: "16px", color: "var(--text-sage)" }}>{report.type}</td>
                    <td style={{ padding: "16px" }}>{report.date}</td>
                    <td style={{ padding: "16px", color: "var(--text-muted)" }}>{report.size}</td>
                    <td style={{ padding: "16px", textAlign: "right" }}>
                      <div style={{ display: "flex", gap: "8px", justifyContent: "flex-end" }}>
                        <button
                          type="button"
                          className="secondary-button"
                          onClick={() => handleDownloadCsv(report)}
                          style={{ padding: "5px 12px", fontSize: "11px", borderRadius: "4px" }}
                        >
                          ⇩ CSV
                        </button>
                        <button
                          type="button"
                          className="primary-button"
                          onClick={() => handleDownloadPdf(report)}
                          style={{ padding: "5px 12px", fontSize: "11px", borderRadius: "4px" }}
                        >
                          ⇩ Dossier
                        </button>
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </section>
    </div>
  );
}
