from pathlib import Path
from datetime import datetime
from uuid import uuid4
import json

from fastapi import (
    APIRouter,
    HTTPException,
    UploadFile,
    File,
    Depends,
)

from fastapi.responses import FileResponse

from sqlalchemy.orm import Session

from app.database import get_db

from app.models.case import (
    MissingPersonCase,
    CCTVVideo,
    CCTVAnalysis,
)

from app.services.cctv_matcher import (
    analyze_cctv_video,
)


# =========================================================
# ROUTER
# =========================================================

router = APIRouter(
    prefix="/api",
    tags=["CCTV Videos"],
)


# =========================================================
# DIRECTORIES
# =========================================================

BASE_DIR = (
    Path(__file__)
    .resolve()
    .parents[2]
)

DATA_DIR = (
    BASE_DIR / "data"
)

VIDEOS_DIR = (
    DATA_DIR / "cctv_videos"
)

RESULTS_DIR = (
    DATA_DIR / "cctv_results"
)


VIDEOS_DIR.mkdir(
    parents=True,
    exist_ok=True,
)

RESULTS_DIR.mkdir(
    parents=True,
    exist_ok=True,
)


# =========================================================
# ALLOWED VIDEO TYPES
# =========================================================

ALLOWED_VIDEO_EXTENSIONS = {
    ".mp4",
    ".avi",
    ".mov",
    ".mkv",
    ".webm",
}


# =========================================================
# HELPER
# =========================================================

async def save_uploaded_video(
    file: UploadFile,
    output_path: Path,
):
    """
    Save uploaded CCTV video in chunks.

    Large CCTV videos are not loaded
    completely into RAM.
    """

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    try:

        with output_path.open("wb") as output_file:

            while True:

                chunk = await file.read(
                    1024 * 1024
                )

                if not chunk:
                    break

                output_file.write(
                    chunk
                )

    finally:

        await file.close()


# =========================================================
# JSON SAFE CONVERSION
# =========================================================

def make_json_safe(value):
    """
    Convert Path objects and nested structures
    into JSON-compatible values.
    """

    if isinstance(value, Path):

        return str(value)

    if isinstance(value, dict):

        return {
            key: make_json_safe(item)
            for key, item in value.items()
        }

    if isinstance(value, list):

        return [
            make_json_safe(item)
            for item in value
        ]

    return value


# =========================================================
# LOAD RESULTS JSON
# =========================================================

def load_results_json(
    results_path: Path,
):
    """
    Load a previously saved CCTV analysis results.json.
    """

    if not results_path.exists():

        raise HTTPException(
            status_code=404,
            detail=(
                "Analysis results file not found."
            ),
        )

    try:

        with results_path.open(
            "r",
            encoding="utf-8",
        ) as json_file:

            return json.load(
                json_file
            )

    except json.JSONDecodeError as exc:

        raise HTTPException(
            status_code=500,
            detail=(
                "Analysis results JSON is invalid: "
                f"{exc}"
            ),
        )

    except Exception as exc:

        raise HTTPException(
            status_code=500,
            detail=(
                "Could not read analysis results: "
                f"{exc}"
            ),
        )


# =========================================================
# FIND ACTUAL MATCHER RESULT DIRECTORY
# =========================================================

def find_matcher_results_path(
    result: dict,
    fallback_directory: Path,
):
    """
    Find the actual results.json generated by
    cctv_matcher.py.

    The matcher creates:

    cctv_results/
        <case_id>/
            <outer_analysis_id>/
                <matcher_analysis_id>/
                    results.json

    The matcher returns result_directory/result_file,
    so those paths are preferred.
    """

    # -----------------------------------------------------
    # 1. Matcher result_directory
    # -----------------------------------------------------

    matcher_directory = result.get(
        "result_directory"
    )

    if matcher_directory:

        matcher_directory = Path(
            matcher_directory
        )

        matcher_results = (
            matcher_directory
            / "results.json"
        )

        if matcher_results.exists():

            return matcher_results

    # -----------------------------------------------------
    # 2. Matcher result_file
    # -----------------------------------------------------

    matcher_results_file = result.get(
        "result_file"
    )

    if matcher_results_file:

        matcher_results_file = Path(
            matcher_results_file
        )

        if matcher_results_file.exists():

            return matcher_results_file

    # -----------------------------------------------------
    # 3. Fallback
    # -----------------------------------------------------

    return (
        fallback_directory
        / "results.json"
    )


# =========================================================
# FIND CASE
# =========================================================

def get_case_or_404(
    case_id: int,
    db: Session,
):
    """
    Return a case or raise HTTP 404.
    """

    case = (
        db.query(MissingPersonCase)
        .filter(
            MissingPersonCase.id == case_id
        )
        .first()
    )

    if case is None:

        raise HTTPException(
            status_code=404,
            detail="Case not found",
        )

    return case


# =========================================================
# FIND ANALYSIS
# =========================================================

def get_analysis_or_404(
    case_id: int,
    analysis_id: str,
    db: Session,
):
    """
    Return a CCTV analysis belonging to
    the requested case.
    """

    analysis = (
        db.query(CCTVAnalysis)
        .filter(
            CCTVAnalysis.case_id == case_id,
            CCTVAnalysis.analysis_id == analysis_id,
        )
        .first()
    )

    if analysis is None:

        raise HTTPException(
            status_code=404,
            detail="Analysis not found",
        )

    return analysis


# =========================================================
# GET RESULTS DIRECTORY
# =========================================================

def get_analysis_results_directory(
    analysis: CCTVAnalysis,
):
    """
    Return the directory containing the
    actual analysis results.json.

    Evidence images are stored beside results.json.
    """

    if not analysis.results_path:

        raise HTTPException(
            status_code=404,
            detail=(
                "Analysis results path is not available."
            ),
        )

    results_path = Path(
        analysis.results_path
    )

    if not results_path.exists():

        raise HTTPException(
            status_code=404,
            detail=(
                "Analysis results file not found."
            ),
        )

    return results_path.parent


# =========================================================
# SAFE EVIDENCE FILENAME
# =========================================================

def get_safe_evidence_filename(
    filename: str,
):
    """
    Prevent directory traversal.

    Only the filename itself is accepted.
    """

    safe_filename = Path(
        filename
    ).name

    if not safe_filename:

        raise HTTPException(
            status_code=400,
            detail="Invalid evidence filename.",
        )

    if safe_filename != filename:

        raise HTTPException(
            status_code=400,
            detail="Invalid evidence filename.",
        )

    return safe_filename


# =========================================================
# CASE-SPECIFIC CCTV ANALYSIS
# =========================================================

@router.post(
    "/cases/{case_id}/videos"
)
async def analyze_case_video(
    case_id: int,
    file: UploadFile = File(
        ...,
        description=(
            "Upload a CCTV video "
            "for this missing-person case"
        ),
    ),
    db: Session = Depends(get_db),
):
    """
    Upload and analyze a CCTV video against
    the reference profile belonging to a
    specific missing-person case.
    """

    # =====================================================
    # 1. FIND CASE
    # =====================================================

    case = get_case_or_404(
        case_id,
        db,
    )

    print()
    print("=" * 60)
    print("CASE FOUND")
    print("=" * 60)
    print(
        f"Case ID: {case.id}"
    )
    print(
        f"Name: {case.name}"
    )
    print("=" * 60)

    # =====================================================
    # 2. VALIDATE VIDEO
    # =====================================================

    if not file.filename:

        raise HTTPException(
            status_code=400,
            detail="No video file provided.",
        )

    original_filename = (
        Path(
            file.filename
        ).name
    )

    extension = (
        Path(
            original_filename
        )
        .suffix
        .lower()
    )

    if extension not in ALLOWED_VIDEO_EXTENSIONS:

        raise HTTPException(
            status_code=400,
            detail=(
                "Unsupported video format. "
                f"Allowed: "
                f"{sorted(ALLOWED_VIDEO_EXTENSIONS)}"
            ),
        )

    # =====================================================
    # 3. FIND REFERENCE PROFILE
    # =====================================================

    reference_profile_path = (
        DATA_DIR
        / "missing_persons"
        / str(case.id)
        / "references"
        / "reference_profile.npz"
    )

    if not reference_profile_path.exists():

        raise HTTPException(
            status_code=400,
            detail=(
                "Reference profile not found for "
                f"case {case.id}. "
                "Upload reference images first."
            ),
        )

    print()
    print(
        f"Reference profile: "
        f"{reference_profile_path}"
    )

    # =====================================================
    # 4. CREATE ANALYSIS ID
    # =====================================================

    analysis_id = (
        datetime.now().strftime(
            "%Y%m%d_%H%M%S"
        )
        + "_"
        + uuid4().hex[:8]
    )

    # =====================================================
    # 5. CREATE VIDEO DIRECTORY
    # =====================================================

    case_video_directory = (
        VIDEOS_DIR
        / str(case.id)
    )

    case_video_directory.mkdir(
        parents=True,
        exist_ok=True,
    )

    # =====================================================
    # 6. UNIQUE VIDEO NAME
    # =====================================================

    video_filename = (
        f"{analysis_id}_"
        f"{original_filename}"
    )

    video_path = (
        case_video_directory
        / video_filename
    )

    # =====================================================
    # 7. CREATE OUTER RESULT DIRECTORY
    # =====================================================

    analysis_result_directory = (
        RESULTS_DIR
        / str(case.id)
        / analysis_id
    )

    analysis_result_directory.mkdir(
        parents=True,
        exist_ok=True,
    )

    # =====================================================
    # 8. SAVE VIDEO
    # =====================================================

    try:

        print()
        print("=" * 60)
        print("CCTV VIDEO UPLOAD")
        print("=" * 60)

        print(
            f"Case ID: {case.id}"
        )

        print(
            f"Case Name: {case.name}"
        )

        print(
            f"Analysis ID: {analysis_id}"
        )

        print(
            f"Original video: "
            f"{original_filename}"
        )

        print(
            f"Saving video to: "
            f"{video_path}"
        )

        await save_uploaded_video(
            file,
            video_path,
        )

        print(
            "Video saved successfully."
        )

    except Exception as exc:

        raise HTTPException(
            status_code=500,
            detail=(
                "Could not save video: "
                f"{exc}"
            ),
        )

    # =====================================================
    # 9. CREATE DATABASE VIDEO RECORD
    # =====================================================

    cctv_video = CCTVVideo(
        case_id=case.id,
        original_filename=(
            original_filename
        ),
        stored_path=str(
            video_path
        ),
        status="processing",
    )

    db.add(
        cctv_video
    )

    db.commit()

    db.refresh(
        cctv_video
    )

    print(
        f"CCTV database ID: "
        f"{cctv_video.id}"
    )

    # =====================================================
    # 10. RUN CCTV ANALYSIS
    # =====================================================

    try:

        print()
        print("=" * 60)
        print("STARTING CCTV ANALYSIS")
        print("=" * 60)

        print(
            f"Case: {case.name}"
        )

        print(
            f"Case ID: {case.id}"
        )

        print(
            f"Profile: "
            f"{reference_profile_path}"
        )

        print(
            f"Video: "
            f"{video_path}"
        )

        print(
            f"Results: "
            f"{analysis_result_directory}"
        )

        result = analyze_cctv_video(

            video_path=video_path,

            output_directory=(
                analysis_result_directory
            ),

            frame_skip=5,

            reference_profile_path=(
                reference_profile_path
            ),
        )

        print()
        print("=" * 60)
        print("CCTV ANALYSIS COMPLETE")
        print("=" * 60)

    except Exception as exc:

        cctv_video.status = "failed"

        db.commit()

        print()
        print("=" * 60)
        print("CCTV ANALYSIS FAILED")
        print("=" * 60)

        print(
            str(exc)
        )

        raise HTTPException(
            status_code=500,
            detail=(
                "CCTV analysis failed: "
                f"{exc}"
            ),
        )

    # =====================================================
    # 11. MAKE RESULT JSON SAFE
    # =====================================================

    result = make_json_safe(
        result
    )

    # =====================================================
    # 12. FIND ACTUAL MATCHER RESULTS.JSON
    # =====================================================

    results_path = (
        find_matcher_results_path(
            result,
            analysis_result_directory,
        )
    )

    # =====================================================
    # 13. ADD APPLICATION INFORMATION
    # =====================================================

    result["case_id"] = (
        case.id
    )

    result["case_name"] = (
        case.name
    )

    result["analysis_id"] = (
        analysis_id
    )

    result["video_path"] = (
        str(video_path)
    )

    result["reference_profile"] = (
        str(reference_profile_path)
    )

    result["results_path"] = (
        str(results_path)
    )

    result["cctv_video_id"] = (
        cctv_video.id
    )

    # =====================================================
    # 14. SAVE FINAL RESULTS.JSON
    # =====================================================

    try:

        results_path.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        with results_path.open(
            "w",
            encoding="utf-8",
        ) as json_file:

            json.dump(
                result,
                json_file,
                indent=4,
                ensure_ascii=False,
            )

    except Exception as exc:

        cctv_video.status = "failed"

        db.commit()

        raise HTTPException(
            status_code=500,
            detail=(
                "Analysis completed, "
                "but results could not "
                f"be saved: {exc}"
            ),
        )

    # =====================================================
    # 15. CALCULATE SUMMARY
    # =====================================================

    matches = result.get(
        "matches",
        [],
    )

    sightings = result.get(
        "sightings",
        [],
    )

    potential_matches = int(
        result.get(
            "potential_matches",
            len(matches),
        )
    )

    confirmed_sightings = int(
        result.get(
            "confirmed_sightings",
            len(sightings),
        )
    )

    # =====================================================
    # 16. BEST SIMILARITY
    # =====================================================

    best_similarity = None

    if sightings:

        similarities = [
            float(
                item["best_similarity"]
            )
            for item in sightings
            if item.get(
                "best_similarity"
            ) is not None
        ]

        if similarities:

            best_similarity = max(
                similarities
            )

    elif matches:

        similarities = [
            float(
                item["similarity"]
            )
            for item in matches
            if item.get(
                "similarity"
            ) is not None
        ]

        if similarities:

            best_similarity = max(
                similarities
            )

    # =====================================================
    # 17. CREATE CCTV ANALYSIS RECORD
    # =====================================================

    cctv_analysis = CCTVAnalysis(

        case_id=case.id,

        video_id=cctv_video.id,

        analysis_id=analysis_id,

        status="completed",

        potential_matches=(
            potential_matches
        ),

        confirmed_sightings=(
            confirmed_sightings
        ),

        best_similarity=(
            best_similarity
        ),

        results_path=str(
            results_path
        ),
    )

    db.add(
        cctv_analysis
    )

    # =====================================================
    # 18. UPDATE VIDEO STATUS
    # =====================================================

    cctv_video.status = (
        "completed"
    )

    db.commit()

    db.refresh(
        cctv_analysis
    )

    # =====================================================
    # 19. FINAL LOG
    # =====================================================

    print()
    print("=" * 60)
    print("ANALYSIS FINISHED")
    print("=" * 60)

    print(
        f"Case ID: {case.id}"
    )

    print(
        f"Video ID: {cctv_video.id}"
    )

    print(
        f"Analysis DB ID: "
        f"{cctv_analysis.id}"
    )

    print(
        f"Analysis ID: "
        f"{analysis_id}"
    )

    print(
        f"Potential matches: "
        f"{potential_matches}"
    )

    print(
        f"Confirmed sightings: "
        f"{confirmed_sightings}"
    )

    print(
        f"Best similarity: "
        f"{best_similarity}"
    )

    print(
        f"Results: "
        f"{results_path}"
    )

    print("=" * 60)

    # =====================================================
    # 20. RESPONSE
    # =====================================================

    return {

        "success": True,

        "case_id":
            case.id,

        "case_name":
            case.name,

        "cctv_video_id":
            cctv_video.id,

        "analysis_db_id":
            cctv_analysis.id,

        "analysis_id":
            analysis_id,

        "status":
            "completed",

        "video":
            str(video_path),

        "reference_profile":
            str(reference_profile_path),

        "potential_matches":
            potential_matches,

        "confirmed_sightings":
            confirmed_sightings,

        "best_similarity":
            best_similarity,

        "results":
            result,

        "results_file":
            str(results_path),
    }


# =========================================================
# GET ALL ANALYSES FOR A CASE
# =========================================================

@router.get(
    "/cases/{case_id}/analyses"
)
def get_case_analyses(
    case_id: int,
    db: Session = Depends(get_db),
):
    """
    Return all CCTV analyses belonging
    to a specific missing-person case.
    """

    # -----------------------------------------------------
    # Verify case
    # -----------------------------------------------------

    case = get_case_or_404(
        case_id,
        db,
    )

    # -----------------------------------------------------
    # Get analyses
    # -----------------------------------------------------

    analyses = (
        db.query(CCTVAnalysis)
        .filter(
            CCTVAnalysis.case_id == case_id
        )
        .order_by(
            CCTVAnalysis.created_at.desc()
        )
        .all()
    )

    # -----------------------------------------------------
    # Build response
    # -----------------------------------------------------

    analysis_list = []

    for analysis in analyses:

        analysis_list.append({

            "id":
                analysis.id,

            "analysis_id":
                analysis.analysis_id,

            "video_id":
                analysis.video_id,

            "status":
                analysis.status,

            "potential_matches":
                analysis.potential_matches,

            "confirmed_sightings":
                analysis.confirmed_sightings,

            "best_similarity":
                analysis.best_similarity,

            "created_at":
                (
                    analysis.created_at.isoformat()
                    if analysis.created_at
                    else None
                ),

            "results_path":
                analysis.results_path,
        })

    return {

        "success":
            True,

        "case_id":
            case.id,

        "case_name":
            case.name,

        "count":
            len(analysis_list),

        "analyses":
            analysis_list,
    }


# =========================================================
# GET SINGLE ANALYSIS
# =========================================================

@router.get(
    "/cases/{case_id}/analyses/{analysis_id}"
)
def get_case_analysis(
    case_id: int,
    analysis_id: str,
    db: Session = Depends(get_db),
):
    """
    Return the complete stored result
    of one CCTV analysis.
    """

    analysis = get_analysis_or_404(
        case_id,
        analysis_id,
        db,
    )

    # -----------------------------------------------------
    # Load results
    # -----------------------------------------------------

    results_path = Path(
        analysis.results_path
    )

    results = load_results_json(
        results_path
    )

    return {

        "success":
            True,

        "case_id":
            case_id,

        "analysis": {

            "id":
                analysis.id,

            "analysis_id":
                analysis.analysis_id,

            "video_id":
                analysis.video_id,

            "status":
                analysis.status,

            "potential_matches":
                analysis.potential_matches,

            "confirmed_sightings":
                analysis.confirmed_sightings,

            "best_similarity":
                analysis.best_similarity,

            "created_at":
                (
                    analysis.created_at.isoformat()
                    if analysis.created_at
                    else None
                ),

            "results_path":
                analysis.results_path,
        },

        "results":
            results,
    }


# =========================================================
# GET CONFIRMED SIGHTINGS
# =========================================================

@router.get(
    "/cases/{case_id}/analyses/{analysis_id}/sightings"
)
def get_confirmed_sightings(
    case_id: int,
    analysis_id: str,
    db: Session = Depends(get_db),
):
    """
    Return only confirmed CCTV sightings.
    """

    analysis = get_analysis_or_404(
        case_id,
        analysis_id,
        db,
    )

    results = load_results_json(
        Path(
            analysis.results_path
        )
    )

    sightings = results.get(
        "sightings",
        [],
    )

    return {

        "success":
            True,

        "case_id":
            case_id,

        "analysis_id":
            analysis_id,

        "count":
            len(sightings),

        "confirmed_sightings":
            sightings,
    }


# =========================================================
# GET ALL POTENTIAL MATCHES
# =========================================================

@router.get(
    "/cases/{case_id}/analyses/{analysis_id}/matches"
)
def get_potential_matches(
    case_id: int,
    analysis_id: str,
    db: Session = Depends(get_db),
):
    """
    Return all raw potential face matches.
    """

    analysis = get_analysis_or_404(
        case_id,
        analysis_id,
        db,
    )

    results = load_results_json(
        Path(
            analysis.results_path
        )
    )

    matches = results.get(
        "matches",
        [],
    )

    return {

        "success":
            True,

        "case_id":
            case_id,

        "analysis_id":
            analysis_id,

        "count":
            len(matches),

        "potential_matches":
            matches,
    }


# =========================================================
# GET ONE EVIDENCE IMAGE
# =========================================================

@router.get(
    "/cases/{case_id}/analyses/{analysis_id}/evidence/{filename}"
)
def get_evidence_image(
    case_id: int,
    analysis_id: str,
    filename: str,
    db: Session = Depends(get_db),
):
    """
    Return one evidence image.

    IMPORTANT:

    Evidence images are stored in the SAME directory
    as the actual matcher results.json.

    Example:

    cctv_results/
        1/
            20260813_205934_e80d4ba7/
                20260813_212539/
                    results.json
                    match_0001.jpg
                    match_0002.jpg
                    match_0005.jpg
    """

    print()
    print("=" * 60)
    print("EVIDENCE IMAGE REQUEST")
    print("=" * 60)

    print(
        f"Case ID: {case_id}"
    )

    print(
        f"Analysis ID: {analysis_id}"
    )

    # -----------------------------------------------------
    # Validate filename
    # -----------------------------------------------------

    safe_filename = (
        get_safe_evidence_filename(
            filename
        )
    )

    print(
        f"Requested: {safe_filename}"
    )

    # -----------------------------------------------------
    # Find analysis
    # -----------------------------------------------------

    analysis = get_analysis_or_404(
        case_id,
        analysis_id,
        db,
    )

    # -----------------------------------------------------
    # Find actual results directory
    # -----------------------------------------------------

    results_directory = (
        get_analysis_results_directory(
            analysis
        )
    )

    evidence_path = (
        results_directory
        / safe_filename
    )

    print(
        f"Found: {evidence_path}"
    )

    print("=" * 60)

    # -----------------------------------------------------
    # Verify file
    # -----------------------------------------------------

    if not evidence_path.exists():

        raise HTTPException(
            status_code=404,
            detail=(
                "Evidence image not found: "
                f"{safe_filename}"
            ),
        )

    if not evidence_path.is_file():

        raise HTTPException(
            status_code=404,
            detail=(
                "Evidence path is not a file."
            ),
        )

    # -----------------------------------------------------
    # Return image
    # -----------------------------------------------------

    return FileResponse(

        path=str(
            evidence_path
        ),

        media_type="image/jpeg",

        filename=safe_filename,
    )


# =========================================================
# GET EVIDENCE GALLERY
# =========================================================

@router.get(
    "/cases/{case_id}/analyses/{analysis_id}/evidence"
)
def get_evidence_gallery(
    case_id: int,
    analysis_id: str,
    db: Session = Depends(get_db),
):
    """
    Return all evidence images belonging
    to an analysis.

    The gallery is generated from the matches
    stored in results.json.
    """

    analysis = get_analysis_or_404(
        case_id,
        analysis_id,
        db,
    )

    # -----------------------------------------------------
    # Load results
    # -----------------------------------------------------

    results = load_results_json(
        Path(
            analysis.results_path
        )
    )

    matches = results.get(
        "matches",
        [],
    )

    sightings = results.get(
        "sightings",
        [],
    )

    # -----------------------------------------------------
    # Build unique evidence list
    # -----------------------------------------------------

    evidence = []

    seen_files = set()

    for match in matches:

        filename = match.get(
            "evidence_image"
        )

        if not filename:
            continue

        filename = Path(
            filename
        ).name

        if filename in seen_files:
            continue

        seen_files.add(
            filename
        )

        evidence.append({

            "filename":
                filename,

            "frame":
                match.get(
                    "frame"
                ),

            "timestamp":
                match.get(
                    "timestamp"
                ),

            "similarity":
                match.get(
                    "similarity"
                ),

            "reference_index":
                match.get(
                    "reference_index"
                ),

            "bounding_box":
                match.get(
                    "bounding_box"
                ),

            "url": (
                f"/api/cases/"
                f"{case_id}/analyses/"
                f"{analysis_id}/evidence/"
                f"{filename}"
            ),

            "is_confirmed":
                False,
        })

    # -----------------------------------------------------
    # Mark confirmed evidence
    # -----------------------------------------------------

    confirmed_files = set()

    for sighting in sightings:

        filename = sighting.get(
            "evidence_image"
        )

        if filename:

            confirmed_files.add(
                Path(
                    filename
                ).name
            )

    for item in evidence:

        if item["filename"] in confirmed_files:

            item["is_confirmed"] = True

    # -----------------------------------------------------
    # Verify physical files
    # -----------------------------------------------------

    results_directory = (
        get_analysis_results_directory(
            analysis
        )
    )

    existing_evidence = []

    for item in evidence:

        evidence_path = (
            results_directory
            / item["filename"]
        )

        if evidence_path.exists():

            existing_evidence.append(
                item
            )

    # -----------------------------------------------------
    # Response
    # -----------------------------------------------------

    return {

        "success":
            True,

        "case_id":
            case_id,

        "analysis_id":
            analysis_id,

        "count":
            len(existing_evidence),

        "evidence":
            existing_evidence,
    }


# =========================================================
# OLD / BACKWARD-COMPATIBLE ENDPOINT
# =========================================================

@router.post(
    "/videos/analyze"
)
async def analyze_uploaded_video(
    file: UploadFile = File(...),
):
    """
    Legacy CCTV analysis endpoint.

    This endpoint does not belong to a
    specific database case.

    It remains available for backward compatibility.
    """

    # =====================================================
    # 1. VALIDATE FILE
    # =====================================================

    if not file.filename:

        raise HTTPException(
            status_code=400,
            detail="No video file provided.",
        )

    original_filename = (
        Path(
            file.filename
        ).name
    )

    extension = (
        Path(
            original_filename
        )
        .suffix
        .lower()
    )

    if extension not in ALLOWED_VIDEO_EXTENSIONS:

        raise HTTPException(
            status_code=400,
            detail=(
                "Unsupported video format. "
                f"Allowed: "
                f"{sorted(ALLOWED_VIDEO_EXTENSIONS)}"
            ),
        )

    # =====================================================
    # 2. CREATE ANALYSIS ID
    # =====================================================

    analysis_id = (
        datetime.now().strftime(
            "%Y%m%d_%H%M%S"
        )
        + "_"
        + uuid4().hex[:8]
    )

    # =====================================================
    # 3. VIDEO PATH
    # =====================================================

    video_path = (
        VIDEOS_DIR
        / (
            f"{analysis_id}_"
            f"{original_filename}"
        )
    )

    # =====================================================
    # 4. RESULT DIRECTORY
    # =====================================================

    output_directory = (
        RESULTS_DIR
        / analysis_id
    )

    output_directory.mkdir(
        parents=True,
        exist_ok=True,
    )

    # =====================================================
    # 5. SAVE + ANALYZE
    # =====================================================

    try:

        await save_uploaded_video(
            file,
            video_path,
        )

        result = analyze_cctv_video(

            video_path=video_path,

            output_directory=(
                output_directory
            ),

            frame_skip=5,
        )

        result = make_json_safe(
            result
        )

        # -------------------------------------------------
        # Find actual matcher results
        # -------------------------------------------------

        results_path = (
            find_matcher_results_path(
                result,
                output_directory,
            )
        )

        results_path.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        # -------------------------------------------------
        # Save results
        # -------------------------------------------------

        with results_path.open(
            "w",
            encoding="utf-8",
        ) as json_file:

            json.dump(
                result,
                json_file,
                indent=4,
                ensure_ascii=False,
            )

        return {

            "success":
                True,

            "analysis_id":
                analysis_id,

            "results":
                result,

            "results_file":
                str(results_path),
        }

    except Exception as exc:

        raise HTTPException(
            status_code=500,
            detail=(
                "CCTV analysis failed: "
                f"{exc}"
            ),
        )